services:
  modelo-api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - APP_NAME
      - HTTP_PORT
      - DATABASE_URL
      - ACCESS_TOKEN_SECRET
      - ACCESS_TOKEN_EXPIRATION
      - REFRESH_TOKEN_SECRET
      - REFRESH_TOKEN_EXPIRATION
    volumes:
      - ../../ssl:/app/ssl
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    networks:
      - srvweb-network

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=modelo
      - POSTGRES_PASSWORD=modelo
      - POSTGRES_DB=modelo
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - srvweb-network

networks:
  srvweb-network:
    driver: bridge

volumes:
  postgres-data:
